# - 2
FROM rasa/rasa-sdk:3.6.10

# Copy code actions vào image
COPY actions /app/actions
WORKDIR /app

# Mở port cho action server
EXPOSE 5055

# Lệnh chạy action server
CMD ["run", "actions", "--port", "5055", "--debug", "--host", "0.0.0.0"]
