# - 5
services:
  - type: web
    name: rasa-core
    env: docker
    # dockerfilePath: Dockerfile
    image: nguyentonganhquan/rasa-core:latest
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5005

  - type: web
    name: action-server
    env: docker
    # dockerfilePath: Dockerfile.action
    image: nguyentonganhquan/action-server:latest
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5055
