# - 5
services:
  - type: web
    name: rasa-core
    env: docker
    image:
      url: nguyentonganahquan/rasa-core:latest
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5005

  - type: web
    name: action-server
    env: docker
    image:
      url: nguyentonganahquan/action-server:latest
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5055


